/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    schools: School;
    contacts: Contact;
    teachers: Teacher;
    programs: Program;
    'lesson-templates': LessonTemplate;
    bookings: Booking;
    lessons: Lesson;
    closures: Closure;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    schools: SchoolsSelect<false> | SchoolsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'lesson-templates': LessonTemplatesSelect<false> | LessonTemplatesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    closures: ClosuresSelect<false> | ClosuresSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * "Admin" adds organisation-wide settings (currently: branding under Globals > Site settings) on top of everything a "Staff" user can already do. It does not restrict day-to-day work -- every signed-in user has full access to Schools, Teachers, Programs, Bookings, and Lessons regardless of role. See src/access/roles.ts for the full definition.
   */
  role: 'admin' | 'staff';
  /**
   * Language for the front-end planning app (/planning, /schools, /teachers, /programs, /settings) — separate from the admin panel's own language picker in the account menu, which only affects /admin.
   */
  preferredLanguage: 'en' | 'nl';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools".
 */
export interface School {
  id: number;
  name: string;
  street?: string | null;
  houseNumber?: string | null;
  /**
   * House number addition, e.g. "A" or "-1".
   */
  addition?: string | null;
  postalCode?: string | null;
  city?: string | null;
  country?: string | null;
  phone?: string | null;
  /**
   * Default room/location for lessons at this school (e.g. "in de klas", "gymlokaal"). Each lesson can still override it.
   */
  defaultLocationNote?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  fullName: string;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  phone?: string | null;
  school: number | School;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: number;
  displayName: string;
  kind: 'person' | 'organisation';
  email?: string | null;
  phone?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Defaults onto every lesson generated from this program. Deferred: whether this feeds subsidy reporting is an open question for after the MVP.
   */
  soort?: ('regulier' | 'maatwerk' | 'cmk' | 'kbw') | null;
  /**
   * How many lesson slots a booking of this program generates by default. Informational once lesson templates exist below — the templates are the actual source of truth.
   */
  defaultLessonCount?: number | null;
  defaultLessonDurationMinutes?: number | null;
  /**
   * Price in euros for the full program.
   */
  price?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-templates".
 */
export interface LessonTemplate {
  id: number;
  program: number | Program;
  /**
   * Position of this lesson within the program (1, 2, 3, ...).
   */
  sequenceNo: number;
  durationMinutes?: number | null;
  /**
   * Pre-fills the teacher on every generated lesson; still editable per lesson.
   */
  defaultTeacher?: (number | null) | Teacher;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  school: number | School;
  program: number | Program;
  /**
   * Class/group, e.g. "3a" or "6/7". Free text on purpose — the real data mixes plain numbers and labels.
   */
  groupLabel?: string | null;
  /**
   * Used to space out the generated lessons; edit individual lesson dates afterward as needed.
   */
  startDate: string;
  /**
   * Replaces the old blauw/oranje/groen/wit cell-colour legend with a real, filterable field.
   */
  status: 'nieuw' | 'aangevraagd_docent' | 'akkoord_docent' | 'akkoord_school';
  note?: string | null;
  /**
   * Set only by the legacy-spreadsheet import script (scripts/legacy-import/) to identify which source row this booking came from, so a later re-run of the same import updates it instead of creating a duplicate. Empty for every booking created through the app itself.
   */
  importRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  booking: number | Booking;
  sequenceNo: number;
  lessonDate: string;
  startTime?: string | null;
  endTime?: string | null;
  /**
   * Copied from the booking at generation time; editable per lesson.
   */
  groupLabel?: string | null;
  teachers?: (number | Teacher)[] | null;
  /**
   * Overrides the school's default location note for this lesson only.
   */
  location?: string | null;
  studentCount?: number | null;
  status: 'nieuw' | 'aangevraagd_docent' | 'akkoord_docent' | 'akkoord_school';
  /**
   * Only set this for the rare lesson that genuinely differs from its program's soort.
   */
  soortOverride?: ('regulier' | 'maatwerk' | 'cmk' | 'kbw') | null;
  remark?: string | null;
  /**
   * Set only by the legacy-spreadsheet import script (scripts/legacy-import/) to identify which source row this lesson came from, so a later re-run of the same import updates it instead of creating a duplicate. Empty for every lesson generated or created through the app itself.
   */
  importRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "closures".
 */
export interface Closure {
  id: number;
  school: number | School;
  /**
   * e.g. "Studiedag" or "Zomervakantie".
   */
  label: string;
  startDate: string;
  /**
   * Leave blank for a single day.
   */
  endDate?: string | null;
  /**
   * Set only by the legacy-spreadsheet import script (scripts/legacy-import/) to identify which source row this closure came from, so a later re-run of the same import updates it instead of creating a duplicate. Empty for every closure created through the app itself.
   */
  importRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'schools';
        value: number | School;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'teachers';
        value: number | Teacher;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'lesson-templates';
        value: number | LessonTemplate;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'closures';
        value: number | Closure;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  preferredLanguage?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools_select".
 */
export interface SchoolsSelect<T extends boolean = true> {
  name?: T;
  street?: T;
  houseNumber?: T;
  addition?: T;
  postalCode?: T;
  city?: T;
  country?: T;
  phone?: T;
  defaultLocationNote?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  fullName?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  school?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  displayName?: T;
  kind?: T;
  email?: T;
  phone?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  soort?: T;
  defaultLessonCount?: T;
  defaultLessonDurationMinutes?: T;
  price?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-templates_select".
 */
export interface LessonTemplatesSelect<T extends boolean = true> {
  program?: T;
  sequenceNo?: T;
  durationMinutes?: T;
  defaultTeacher?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  school?: T;
  program?: T;
  groupLabel?: T;
  startDate?: T;
  status?: T;
  note?: T;
  importRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  booking?: T;
  sequenceNo?: T;
  lessonDate?: T;
  startTime?: T;
  endTime?: T;
  groupLabel?: T;
  teachers?: T;
  location?: T;
  studentCount?: T;
  status?: T;
  soortOverride?: T;
  remark?: T;
  importRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "closures_select".
 */
export interface ClosuresSelect<T extends boolean = true> {
  school?: T;
  label?: T;
  startDate?: T;
  endDate?: T;
  importRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Shown in the left nav instead of "Easy Course Scheduler". Leave blank to use the default.
   */
  organisationName?: string | null;
  /**
   * Shown in the left nav next to (or instead of) the organisation name.
   */
  logo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organisationName?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}